### ISSUE TITLE
Help towards timeframes

### ISSUE THREAD

**Issue by Simonxyz123** [Thomas-Gelf/icingaweb2-module-reporting#10]
I need some help with the timeframes. I have created the timeframes.ini file as descripted in the ReadME but i still dont have the Options in Icingaweb2

**Comment by Caez83** [comment]
Hello

I have the same problem because i don't real carrefully the documentation.
You have to create the file in the module configuration dir and not in the enabledModule configuration dir.

I'm using debian:
The module are in /usr/share/icingaweb2/modules
When a module is enabled, a copy is placed in the /etc/icingaweb2/enabledModules/ dir but it's not the modules configuration directory 

the timeframes.ini file have to be in the modules configuration
/etc/icingaweb2/modules

Create the reporting dir
/etc/icinga2/modules/reporting and place the file into

# ls /etc/icingaweb2/modules/reporting/
timeframes.ini

**Comment by Simonxyz123** [comment]
Okay now i can see the timeframes in the Dropdown menu. I get an error if i try to pull a report then.

Icingaweb2 says Syntax error: (I copied the timeframes.ini from the README.

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION icinga.icinga_availability_slatime does not exist, query was: SELECT ho.name1 AS hostname, icinga_availability_slatime(ho.object_id, '2019-01-03 10:34:04', '2019-01-10 10:34:04', NULL) AS one_week FROM icinga_objects AS ho
INNER JOIN icinga_hostgroup_members AS hgm ON ho.object_id = hgm.host_object_id
INNER JOIN icinga_hostgroups AS hg ON hg.hostgroup_id = hgm.hostgroup_id
INNER JOIN icinga_objects AS hgo ON hgo.object_id = hg.hostgroup_object_id AND hgo.is_active = 1 WHERE (hgo.name1 = 'Windows') AND (ho.is_active = 1) ORDER BY one_week ASC, hostname ASC

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/reporting/library/Reporting/Report/HostslaReport.php(27): Zend_Db_Adapter_Abstract->fetchAll(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/reporting/library/Reporting/Report/SlaReport.php(23): Icinga\Module\Reporting\Report\HostslaReport->getResult()
#6 /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Hook/ReportHook.php(91): Icinga\Module\Reporting\Report\SlaReport->getViewData()
#7 zend.view:///usr/share/icingaweb2/modules/reporting/application/views/scripts/report/show.phtml(12): Icinga\Module\Reporting\Web\Hook\ReportHook->render(Object(Icinga\Web\View))
#8 /usr/share/php/Icinga/Web/View.php(259): include(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#20 {main}
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION icinga.icinga_availability_slatime does not exist

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php(219): PDOStatement->execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#4 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#5 /usr/share/icingaweb2/modules/reporting/library/Reporting/Report/HostslaReport.php(27): Zend_Db_Adapter_Abstract->fetchAll(Object(Zend_Db_Select))
#6 /usr/share/icingaweb2/modules/reporting/library/Reporting/Report/SlaReport.php(23): Icinga\Module\Reporting\Report\HostslaReport->getResult()
#7 /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Hook/ReportHook.php(91): Icinga\Module\Reporting\Report\SlaReport->getViewData()
#8 zend.view:///usr/share/icingaweb2/modules/reporting/application/views/scripts/report/show.phtml(12): Icinga\Module\Reporting\Web\Hook\ReportHook->render(Object(Icinga\Web\View))
#9 /usr/share/php/Icinga/Web/View.php(259): include(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#20 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#21 {main}

**Comment by Caez83** [comment]
Import the sql files present on the shema directory : https://github.com/Thomas-Gelf/icingaweb2-module-reporting/tree/master/schema

**Comment by Simonxyz123** [comment]
Hello Caez83, sorry but im new to icinga2 and im not sure where and how to import the sql files. So in which Database and maybe you got a command example for me.

**Comment by Caez83** [comment]
You have to enable the icinga ido module if it's not enabled 
After, you can find the ido database informations : 

/etc/icinga2/features-enabled/ido-mysql.conf 
/**
 * The db_ido_mysql library implements IDO functionality
 * for MySQL.
 */

library "db_ido_mysql"

object IdoMysqlConnection "ido-mysql" {
  user = "user",
  password = "password",
  host = "host",
  database = "database"
}

Go to the schema directory then import the sql file (replace user, host,  password, database and file )
mysql -h host -u user -ppassword database < file.sql

**Comment by Thomas-Gelf** [comment]
As the [README](../README.md) states, this is a prototype for experienced users. It will not be dropped anytime soon, but now there is an [official one](https://github.com/Icinga/icingaweb2-module-reporting) available. That one will be a better fit for you.
