### ISSUE TITLE
Sending reports via mail

### ISSUE THREAD

**Issue by benohara** [Thomas-Gelf/icingaweb2-module-reporting#12]
Dont see this documented anywhere, but assuming i should be able to mail the reports from cron?  However, I get this issue when trying to use the cli mail command

[root@XXXXXX reporting]# icingacli reporting
PHP Fatal error:  Uncaught Error: Call to a member function getDownloadUrl() on null in zend.view:///usr/share/icingaweb2/modules/reporting/application/views/scripts/reports/sla.phtml:4
Stack trace:
#0 /usr/share/php/Icinga/Web/View.php(259): include()
#1 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Partial.php(106): Zend_View_Abstract->render(NULL)
#3 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(345): Zend_View_Helper_Partial->partial('reports/sla.pht...', NULL, Array)
#4 /usr/share/php/Icinga/Web/View.php(278): Zend_View_Abstract->__call('partial', Array)
#5 /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Hook/ReportHook.php(98): Icinga\Web\View->__call('partial', Array)
#6 /usr/share/icingaweb2/modules/reporting/application/clicommands/MailCommand.php(46): Icinga\Module\Reporting\Web\Hook\ReportHook->render(Object(Icinga\Web\View))
#7 /usr/share/icingaweb2/modules/reporting/a in zend.view:///usr/share/icingaweb2/modules/reporting/application/views/scripts/reports/sla.phtml on line 4
<span class="actions">

Fatal error: Uncaught Error: Call to a member function getDownloadUrl() on null in zend.view:///usr/share/icingaweb2/modules/reporting/application/views/scripts/reports/sla.phtml:4
Stack trace:
#0 /usr/share/php/Icinga/Web/View.php(259): include()
#1 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Partial.php(106): Zend_View_Abstract->render(NULL)
#3 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(345): Zend_View_Helper_Partial->partial('reports/sla.pht...', NULL, Array)
#4 /usr/share/php/Icinga/Web/View.php(278): Zend_View_Abstract->__call('partial', Array)
#5 /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Hook/ReportHook.php(98): Icinga\Web\View->__call('partial', Array)
#6 /usr/share/icingaweb2/modules/reporting/application/clicommands/MailCommand.php(46): Icinga\Module\Reporting\Web\Hook\ReportHook->render(Object(Icinga\Web\View))
#7 /usr/share/icingaweb2/modules/reporting/a in zend.view:///usr/share/icingaweb2/modules/reporting/application/views/scripts/reports/sla.phtml on line 4

**Comment by Thomas-Gelf** [comment]
As the [README](../README.md) states, this is a prototype for experienced users. It will not be dropped anytime soon, but now there is an [official one](https://github.com/Icinga/icingaweb2-module-reporting) available. That one will be a better fit for you.
