### ISSUE TITLE
Error importing refresh_outofslaperiods-procedure

### ISSUE THREAD

**Issue by Mikesch-mp** [Thomas-Gelf/icingaweb2-module-reporting#3]
I get an error during import of refresh_outofslaperiods-procedure.sql

```SQL
ERROR 1064 (42000) at line 6: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UNION

              SELECT
                @day_offset := CASE
  ' at line 96
```

My MySQL (MariaDB) Version:

```
[root@koelin01 schema]# mysqld --version
mysqld  Ver 10.2.14-MariaDB for Linux on x86_64 (MariaDB Server)
```

**Comment by Thomas-Gelf** [comment]
Did you run the file via `mysql dbname < whatever.sql` or did you paste it to your MySQL console? Some client/server/network combinations (especially putty, but not only) do not play nice with the MySQL console, and pasting large chunks of SQL often corrupts pasted data.

**Comment by Mikesch-mp** [comment]
I tried to import via `mysql .... dname < sql.sql`

**Comment by Thomas-Gelf** [comment]
I pushed a small change, could you please try again?

**Comment by Mikesch-mp** [comment]
Worked :) Thank you

**Comment by Thomas-Gelf** [comment]
You're welcome.
