### ISSUE TITLE
Required parameter 'host' missing

### ISSUE THREAD

**Issue by gonzalo-** [Thomas-Gelf/icingaweb2-module-reporting#7]
Hello,

Thanks for this report module! I have some issue with hosts:

`#0 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostController.php(30): Icinga\Web\UrlParams->getRequired(String)
#1 /usr/share/php/Icinga/Web/Controller/ActionController.php(152): Icinga\Module\Monitoring\Controllers\HostController->init()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#7 {main}`

Icingaweb2 version is 2.6.1
Reporting module commit: f0c11f8e8be73cdd669998d52b2c22434f65a8f4

The broken URL looks like:

`/icingaweb2/reporting/report/show#!/icingaweb2/monitoring/host/show?host_name=${SOMEHOST}`

It's working fine if I change it to:

`/icingaweb2/reporting/report/show#!/icingaweb2/monitoring/host/show?host=${SOMEHOST}`

Thanks.

**Comment by Thomas-Gelf** [comment]
I was sure this has already been fixed, seems that it wasn't. Thanks for reporting it, please try again.

**Comment by Thomas-Gelf** [comment]
Found it, there was a pending pull request.

**Comment by gonzalo-** [comment]
Now another thing is broken ;)

`

script 'reports/sla.phtml' not found in path (/usr/share/icingaweb2/modules/reporting/application/views/scripts/:/usr/share/icingaweb2/modules/reporting/application/views/scripts/)

#0 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(873): Zend_View_Abstract->_script(String)
#1 /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Partial.php(106): Zend_View_Abstract->render(String)
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(345): Zend_View_Helper_Partial->partial(String, String, Array)
#3 /usr/share/php/Icinga/Web/View.php(278): Zend_View_Abstract->__call(String, Array)
#4 /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Hook/ReportHook.php(104): Icinga\Web\View->__call(String, Array)
#5 zend.view:///usr/share/icingaweb2/modules/reporting/application/views/scripts/report/show.phtml(12): Icinga\Module\Reporting\Web\Hook\ReportHook->render(Object(Icinga\Web\View))
#6 /usr/share/php/Icinga/Web/View.php(259): include(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#18 {main}`

**Comment by Thomas-Gelf** [comment]
Could this be an error on your side? Like a strict umask & git pull? Please double-check, this file should be there, eventually permissions are wrong:

    /usr/share/icingaweb2/modules/reporting/application/views/scripts/reports/sla.phtml

**Comment by gonzalo-** [comment]
Yup, that fixed it, but on the first git clone work our-of-the-box.

Thanks for the quick respond.

**Comment by Thomas-Gelf** [comment]
Eventually you had another umask on the first git clone. Glad to hear that it works.
