### ISSUE TITLE
Where to get the "Configured Reports" section?

### ISSUE THREAD

**Issue by shsubramanian** [Thomas-Gelf/icingaweb2-module-reporting#9]
I saw the screenshots at https://github.com/Icinga/icingaweb2/issues/104. How do i get the "Configured Reports" section?

![47016066-fa317680-d14e-11e8-8b0b-73f989d7a501](https://user-images.githubusercontent.com/2324254/49918445-35d78b00-fec9-11e8-9d2f-ae3d97dcaba4.png)

**Comment by benhartwich** [comment]
Also searching for a how to install your module. Would be great, if you can provide more details on how to run your module.

**Comment by Thomas-Gelf** [comment]
I'm sorry @benhartwich, work on this has been stopped in favor of the official [Icinga Reporting module](https://github.com/Icinga/icingaweb2-module-reporting). Above design drafts have been provided to the responsible person, but the involved team decided to opt for a custom layout.
